[build]
  # Build command for the frontend
  command = "npm run build"
  # Publish directory (where the built frontend files are)
  publish = "dist"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Ignore backend files during build
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://your-railway-url.railway.app/api/:splat"
  status = 200
  force = true 